require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Metrics/MethodLength:
  Exclude:
    - spec/support/mocks/jira_api_responses.rb

Rails/FilePath:
  Enabled: false

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Enabled: false
